<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OM427-Sumit-Taneja.local" name="Test" tests="3" failures="1" timestamp="28 Mar 2017 23:57:57 GMT" time="0.052" errors="0">
  <testcase name="testLoginFailure" time="0.022" classname="com.outware.test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.outware.test.LoginTest.testLoginFailure(LoginTest.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLoginFailure -->
  <testcase name="testLoginLocked" time="0.002" classname="com.outware.test.LoginTest"/>
  <testcase name="testLoginSuccess" time="0.0" classname="com.outware.test.LoginTest"/>
</testsuite> <!-- Test -->
